---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/objave/en
  label: News/English
  create: documents
  match: "*.md"
- type: directory
  path: content/objave
  label: News
  create: documents
  match: "*.md"
  exclude: en/*.md
- type: directory
  path: content/pages/en
  label: Pages/English
  create: documents
  match: "*.md"
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "*.md"
  exclude: en/*.md
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
